name: deploy

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        cd python-greetings
        pip install -r requirements.txt

    - name: Stop existing app
      run: |
        cd python-greetings
        pm2 delete greetings-app-$ENVIRONMENT & EXIT /B 0

    - name: Start app
      run: |
        cd python-greetings
        pm2 start app.py --name greetings-app-$ENVIRONMENT -- --port $PORT