name: deploy

runs:
  using: "composite"
  steps:      
    - name: Stop existing app
      working-directory: python-greetings
      run: pm2 delete greetings-app-$ENVIRONMENT
      shell: powershell
    - name: Start app
      working-directory: python-greetings
      run: pm2 start app.py --name greetings-app-$ENVIRONMENT -- --port $PORT
      shell: powershell