name: 'deploy'
inputs:
  ENVIRONMENT:
    description: ' env variable'
    required: true
    default: 'dev'
  PORT:
    description: ' port variable'
    required: true
    default: 7001
runs:
  using: 'composite'
  steps:
    - name: 'Stop existing app'
      shell: powershell
      run: pm2 delete greetings-app-${{ inputs.ENVIRONMENT }}

    - name: 'Start app'
      shell: powershell
      run: pm2 start app.py --name greetings-app-${{ inputs.ENVIRONMENT }} -- --port ${{ inputs.PORT }}
