name: 'deploy'
inputs:
  ENVIRONMENT:
    description: ' env variable'
    required: true
  PORT:
    description: ' port variable'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Stop existing app'
      shell: powershell
      run: pm2 delete greetings-app-${{ env.ENVIRONMENT }}

    - name: 'Start app'
      shell: powershell
      run: pm2 start app.py --name greetings-app-${{ env.ENVIRONMENT }} -- --port ${{ env.PORT }}
