name: 'deploy'

runs:
  using: 'composite'
  steps:
    - name: 'Stop existing app'
      run: pm2 delete greetings-app-${{inputs.environment}}
      shell: powershell

    - name: 'Start app'
      run: pm2 start app.py --name greetings-app-${{inputs.environment}} -- --port ${{inputs.port}}
      shell: powershell