name: Python Greetings Pipeline

on:
  push:
    branches:
      - main

env:
  DEV_PORT: "7001"
  STAGING_PORT: "7002"
  PREPROD_PORT: "7003"
  PROD_PORT: "7004"

jobs:
  install-pip-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Clone python-greetings Repository
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Install Pip Dependencies
        working-directory: python-greetings
        run: |
          pip install -r requirements.txt

  deploy-dev:
    needs: install-pip-deps
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to dev
      - uses: ./.github/actions/deploy
        env:
          ENVIRONMENT: "dev"
          PORT: ${{ env.DEV_PORT }}

  test-dev:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Clone course-js-api-framework repository
      - uses: ./.github/actions/test
        with:
          repository: mtararujs/course-js-api-framework
          ref: main
          path: course-js-api-framework

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test-dev
    steps:
      - name: Deploy to staging
      - uses: ./.github/actions/deploy
        env:
          ENVIRONMENT: "staging"
          PORT: ${{ env.STAGING_PORT }}
      - name: Stop existing staging service
        run: pm2 delete greetings-app-staging & set "errorlevel=0"

      - name: Start staging service
        working-directory: ./python-greetings
        run: pm2 start app.py --name greetings-app-staging -- --port ${{ env.STAGING_PORT }}

  test-staging:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Clone course-js-api-framework repository
      - uses: ./.github/actions/test
        with:
          repository: mtararujs/course-js-api-framework
          ref: main
          path: course-js-api-framework

  deploy-preprod:
    runs-on: ubuntu-latest
    needs: test-staging
    steps:
      - name: Deploy to preprod
      - uses: ./.github/actions/deploy
        env:
          ENVIRONMENT: "preprod"
          PORT: ${{ env.PREPROD_PORT }}


  test-preprod:
    runs-on: ubuntu-latest
    needs: deploy-preprod
    steps:
      - name: Clone course-js-api-framework repository
      - uses: ./.github/actions/test
        with:
          repository: mtararujs/course-js-api-framework
          ref: main
          path: course-js-api-framework


  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-preprod
    steps:
      - name: Deploy to prod
      - uses: ./.github/actions/deploy
        env:
          ENVIRONMENT: "prod"
          PORT: ${{ env.PROD_PORT }}
